# Site Configuration
titleBase: Formix
favicon: favicon.ico

# Social media links
social:
  - name: pub.dev
    url: https://pub.dev/packages/formix
  - name: GitHub
    url: https://github.com/shreemanarjun/formix